# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml

# Listen on port 8080
Port: 8080
# End users connect over SSL on port 443
ExternalSecure: true
ExternalPort: 443

# Static DB configuration. Any dynamic values set as ENV vars.
Database:
  postgres:
    User:
      SSL:
        Mode: 'require'
    Admin:
      SSL:
        Mode: 'require'

# Logging
Log:
  Level: 'info'
